### ISSUE TITLE
Duplicate definition of PRIX

### ISSUE THREAD

**Issue by vser1** [Ada-bindings-project/a-pcre#1]
Hi!

Trying to build the project, I encounter two issues:

* `.gen` is not in the gpr include dirs
* My `/usr/include/inttypes.h` defines both `PRIx8` and `PRIX8` (same for other macros). The generated `pcre-low_level-inttypes_h.ads` has then conflicting declarations for these types.

Do you have workarounds?

Regards

**Comment by persan** [comment]
Hi
First, this is by design the flow is: 
1. header-files -> generates ads-files to the .gen/ folder
2. only the required files are copied to src/gen
3. The .sed scripts defined in folder sed/ is applied.
4. Done
Second question:
The generation is optional, this is now reflected in the Makefile, the main objective at the moment is to get the examples running by completing the pcre.matcher body,
By the way which operating system and what version.
/Regards
/P

**Comment by vser1** [comment]
I'm running Ubuntu 20.04 (shipped with a glibc 2.31)
